# Generated by Django 4.2.5 on 2023-11-15 02:06

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_blog_imagen_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrenador',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='Logro',
        ),
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='blog_imagen'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
