# Generated by Django 4.2.5 on 2023-11-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_entrenador_delete_jugador_delete_logro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(upload_to='blog_imagen'),
        ),
    ]
