# Generated by Django 4.2.5 on 2023-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blog_imagen'),
        ),
    ]
