# Generated by Django 4.2.5 on 2023-10-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=200)),
                ('cuerpo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
